name = "Death Note"
author = "DartRuffian"
prefix = "dnt"
mainprefix = "z"

[version]
path = "addons/main/script_version.hpp"
git_hash = 0

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "logo_dnt.png",
    "logo_dnt_ca.paa",
    "LICENSE.md",
    "README.md",
]
exclude = []

[properties]
author = "DartRuffian"